### ISSUE TITLE
Integration of cmp-tailwind-colors with LazyVim config

### ISSUE THREAD

**Issue by Armadillidiid** [js-everts/cmp-tailwind-colors#1]
I'm having trouble integrating cmp-tailwind-colors with my LazyVim config. I tried integrating it alongside the default LazyVim icons, but I keep getting an error. I'm not very familiar with Lua, so I was wondering if someone could help me out.

Here's the formatting section of my nvim-cmp configuration:

```lua
        formatting = {
            -- format = require("cmp-tailwind-colors").format
          format = function(_, item)
            local icons = require("lazyvim.config").icons.kinds
            if icons[item.kind] then
              item.kind = icons[item.kind] .. item.kind
            end
            return item
          end,
        },

```

Any help would be greatly appreciated.

**Comment by js-everts** [comment]
Whats the error you got?. Is tailwind LSP running?

Something like this should work.

```lua
formatting = {
  format = function(entry, item)
    item = require("cmp-tailwind-colors").format(entry, item)
    local icons = require("lazyvim.config").icons.kinds
    if icons[item.kind] then
      item.kind = icons[item.kind] .. item.kind
    end
    return item
  end,
}
```

**Comment by Armadillidiid** [comment]
Thanks, your solution worked. And yes, tailwind LSP was running. I apologize for not providing the specific error message earlier. I'll make sure to include that in future issue reports to provide more context if there be any.
