### ISSUE TITLE
Error: 'blend' is not an integral Number

### ISSUE THREAD

**Issue by ghost** [js-everts/cmp-tailwind-colors#2]
If the location of the star signifies the place that triggers the error, then the following query `shadow-white/*` raises the error mentioned in the title. The error points to https://github.com/js-everts/cmp-tailwind-color/blob/1d8dbec8549871914b536473249b9524f778f799/lua/cmp-tailwind-colors/init.lua#L78

Adding
```lua
hl_opts.blend = tonumber(hl_opts.blend, 2)
```
before the call to `vim.api.nvim_set_hl` fixes the issue

**Comment by js-everts** [comment]
Fixed by eeb2273
