### ISSUE TITLE
[BUG] no longer showing colors in completion menu

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [js-everts/cmp-tailwind-colors#4]
With the latest tailwindcss-language-server updates (0.0.17 & 0.0.18), cmp-tailwind-colors no longer provides a colored completion menu
![Screenshot_2024-06-27-03-03-42-90_84d3000e3f4017145260f7618db1d683](https://github.com/js-everts/cmp-tailwind-colors/assets/76727386/dacd1eb7-eb89-43ea-b08b-904ec0ea46ac)

**Comment by js-everts** [comment]
Fixed by e540de6
